export const performanceMetrics = {
  processingSpeed: {
    value: '18 hours',
    benchmark: '<24 hours',
    status: 'Ahead of target',
    trend: '↓ 5% faster than last month',
  },
  accuracy: {
    value: '99.2%',
    details: '1 error in last 500+ invoices',
    benchmark: '98%+',
    status: 'Excellent',
  },
  budgetUtilization: {
    value: '47%',
    range: '25% to 89%',
    details: '2 participants at >80%, 3 at <25%',
    status: 'Healthy',
  },
  satisfaction: {
    value: '4.7/5',
    details: 'Based on last 30 days feedback',
    comments: 'Fast payment, transparent, helpful team',
    status: 'Excellent',
  },
};

export const dailyInvoicesProcessed = [
  { date: '25 Jan', count: 42 },
  { date: '26 Jan', count: 38 },
  { date: '27 Jan', count: 45 },
  { date: '28 Jan', count: 51 },
  { date: '29 Jan', count: 47 },
  { date: '30 Jan', count: 33 },
  { date: '31 Jan', count: 36 },
  { date: '1 Feb', count: 44 },
  { date: '2 Feb', count: 49 },
  { date: '3 Feb', count: 53 },
  { date: '4 Feb', count: 41 },
  { date: '5 Feb', count: 39 },
  { date: '6 Feb', count: 55 },
  { date: '7 Feb', count: 48 },
  { date: '8 Feb', count: 35 },
  { date: '9 Feb', count: 37 },
  { date: '10 Feb', count: 46 },
  { date: '11 Feb', count: 52 },
  { date: '12 Feb', count: 43 },
  { date: '13 Feb', count: 40 },
  { date: '14 Feb', count: 57 },
  { date: '15 Feb', count: 50 },
  { date: '16 Feb', count: 34 },
  { date: '17 Feb', count: 38 },
  { date: '18 Feb', count: 44 },
  { date: '19 Feb', count: 48 },
  { date: '20 Feb', count: 56 },
  { date: '21 Feb', count: 41 },
  { date: '22 Feb', count: 59 },
  { date: '23 Feb', count: 45 },
];

export const budgetUtilizationDistribution = {
  green0_25: 15,
  blue25_75: 20,
  orange75_100: 10,
  red_over100: 2,
};

export const processingTimeDistribution = {
  sameDay: 80,
  oneDay: 15,
  twoPlusDays: 5,
};

export interface AuditEntry {
  id: string;
  timestamp: string;
  action: string;
  participant: string;
  details: string;
  status: string;
}

export const auditTrail: AuditEntry[] = [
  {
    id: 'AUD-001',
    timestamp: '24 Feb 2026, 3:15 PM',
    action: 'Invoice Approved',
    participant: 'James Thompson',
    details: 'INV-2026-0401 - Active Kids Physio - $350',
    status: 'Completed',
  },
  {
    id: 'AUD-002',
    timestamp: '24 Feb 2026, 2:50 PM',
    action: 'Invoice Approved',
    participant: 'Emma Park',
    details: 'INV-2026-0402 - Communication Plus - $280',
    status: 'Completed',
  },
  {
    id: 'AUD-003',
    timestamp: '24 Feb 2026, 2:30 PM',
    action: 'Invoice Flagged',
    participant: 'Liam Chen',
    details: 'INV-2026-0403 - Physio Plus - $320 - Pricing mismatch',
    status: 'Pending Review',
  },
  {
    id: 'AUD-004',
    timestamp: '24 Feb 2026, 1:45 PM',
    action: 'Duplicate Detected',
    participant: 'Noah Williams',
    details: 'INV-2026-0404 - Active Kids Physio - $350',
    status: 'Action Required',
  },
  {
    id: 'AUD-005',
    timestamp: '24 Feb 2026, 11:20 AM',
    action: 'Budget Alert Raised',
    participant: 'Sophie Rodriguez',
    details: 'Assistive Tech category at 100% utilization',
    status: 'Action Required',
  },
  {
    id: 'AUD-006',
    timestamp: '24 Feb 2026, 10:00 AM',
    action: 'New Participant Onboarded',
    participant: 'Zara Khan',
    details: 'Plan P-2026-001043 created, awaiting provider setup',
    status: 'In Progress',
  },
  {
    id: 'AUD-007',
    timestamp: '23 Feb 2026, 4:30 PM',
    action: 'Payment Batch Processed',
    participant: 'Multiple',
    details: '$4,550 paid to 12 providers',
    status: 'Completed',
  },
  {
    id: 'AUD-008',
    timestamp: '23 Feb 2026, 3:00 PM',
    action: 'Invoice Approved',
    participant: 'Charlotte Adams',
    details: 'INV-2026-0406 - Education Support Services - $500',
    status: 'Completed',
  },
  {
    id: 'AUD-009',
    timestamp: '23 Feb 2026, 1:15 PM',
    action: 'Plan Review Reminder Sent',
    participant: 'Emma Park',
    details: 'Plan review due in 27 days - reminder sent to participant',
    status: 'Completed',
  },
  {
    id: 'AUD-010',
    timestamp: '22 Feb 2026, 4:00 PM',
    action: 'Invoice Approved',
    participant: 'Oliver Taylor',
    details: 'INV-2026-0407 - Active Kids Physio - $175',
    status: 'Completed',
  },
  {
    id: 'AUD-011',
    timestamp: '22 Feb 2026, 2:30 PM',
    action: 'Provider Documentation Flagged',
    participant: 'N/A',
    details: 'Active Kids Physio - Insurance expiring 15 Mar 2026',
    status: 'Pending',
  },
  {
    id: 'AUD-012',
    timestamp: '21 Feb 2026, 3:45 PM',
    action: 'Invoice Approved',
    participant: 'Amelia Johnson',
    details: 'INV-2026-0408 - Communication Plus - $150',
    status: 'Completed',
  },
  {
    id: 'AUD-013',
    timestamp: '21 Feb 2026, 11:00 AM',
    action: 'Budget Review Completed',
    participant: 'William Walker',
    details: 'Budget at 80% utilization - marked for monitoring',
    status: 'Completed',
  },
  {
    id: 'AUD-014',
    timestamp: '20 Feb 2026, 4:15 PM',
    action: 'Invoice Rejected',
    participant: 'Noah Williams',
    details: 'Duplicate invoice rejected - original already processed',
    status: 'Completed',
  },
  {
    id: 'AUD-015',
    timestamp: '20 Feb 2026, 2:00 PM',
    action: 'Provider Query Sent',
    participant: 'Liam Chen',
    details: 'Queried Physio Plus about pricing for initial assessment',
    status: 'Awaiting Response',
  },
  {
    id: 'AUD-016',
    timestamp: '19 Feb 2026, 3:30 PM',
    action: 'Invoice Approved',
    participant: 'Daniel King',
    details: 'INV-2026-0390 - Therapy Works - $420',
    status: 'Completed',
  },
  {
    id: 'AUD-017',
    timestamp: '19 Feb 2026, 1:00 PM',
    action: 'Plan Variation Requested',
    participant: 'Liam Chen',
    details: 'Assistive Tech budget increase requested - $500 additional',
    status: 'Pending NDIA',
  },
  {
    id: 'AUD-018',
    timestamp: '18 Feb 2026, 4:00 PM',
    action: 'Participant Meeting Completed',
    participant: 'Michael Foster',
    details: 'Plan review preparation meeting held',
    status: 'Completed',
  },
  {
    id: 'AUD-019',
    timestamp: '18 Feb 2026, 10:30 AM',
    action: 'Invoice Approved',
    participant: 'Grace Lewis',
    details: 'INV-2026-0385 - Support Services QLD - $290',
    status: 'Completed',
  },
  {
    id: 'AUD-020',
    timestamp: '17 Feb 2026, 3:00 PM',
    action: 'New Provider Linked',
    participant: 'James Thompson',
    details: 'Transport Assist added as provider for James Thompson',
    status: 'Completed',
  },
];
