export type InvoiceStatus = 'Pending' | 'Approved' | 'Paid';

export interface Invoice {
  id: string;
  dateSubmitted: string;
  provider: string;
  serviceType: string;
  amount: number;
  status: InvoiceStatus;
  paidDate?: string;
  description?: string;
  rate?: string;
  servicePeriod?: string;
  transactionRef?: string;
}

export const invoices: Invoice[] = [
  {
    id: 'INV-001',
    dateSubmitted: '24 Feb 2026',
    provider: 'Active Kids Physio',
    serviceType: 'Physiotherapy',
    amount: 350,
    status: 'Pending',
    description: '2x 45-min physiotherapy sessions',
    rate: '$175/session',
    servicePeriod: '17–21 Feb 2026',
  },
  {
    id: 'INV-002',
    dateSubmitted: '22 Feb 2026',
    provider: 'Communication Plus',
    serviceType: 'Speech Therapy',
    amount: 280,
    status: 'Pending',
    description: '1x 60-min + 1x 30-min speech therapy session',
    rate: '$180/session',
    servicePeriod: '20 Feb 2026',
  },
  {
    id: 'INV-003',
    dateSubmitted: '20 Feb 2026',
    provider: 'Education Support Services',
    serviceType: 'School Support (5 days)',
    amount: 500,
    status: 'Approved',
    description: '5 days school support assistance',
    rate: '$100/day',
    servicePeriod: '10–14 Feb 2026',
  },
  {
    id: 'INV-004',
    dateSubmitted: '18 Feb 2026',
    provider: 'Active Kids Physio',
    serviceType: 'Physiotherapy',
    amount: 350,
    status: 'Approved',
    description: '2x 45-min physiotherapy sessions',
    rate: '$175/session',
    servicePeriod: '10–14 Feb 2026',
  },
  {
    id: 'INV-005',
    dateSubmitted: '15 Feb 2026',
    provider: 'Communication Plus',
    serviceType: 'Speech Therapy',
    amount: 280,
    status: 'Paid',
    paidDate: '15 Feb',
    description: '1x 60-min speech therapy session + review',
    rate: '$180/session',
    servicePeriod: '13 Feb 2026',
    transactionRef: 'TXN-20260215-001',
  },
  {
    id: 'INV-006',
    dateSubmitted: '13 Feb 2026',
    provider: 'Active Kids Physio',
    serviceType: 'Physiotherapy',
    amount: 350,
    status: 'Paid',
    paidDate: '14 Feb',
    description: '2x 45-min physiotherapy sessions',
    rate: '$175/session',
    servicePeriod: '10–12 Feb 2026',
    transactionRef: 'TXN-20260214-002',
  },
  {
    id: 'INV-007',
    dateSubmitted: '11 Feb 2026',
    provider: 'Education Support Services',
    serviceType: 'School Support (5 days)',
    amount: 500,
    status: 'Paid',
    paidDate: '12 Feb',
    description: '5 days school support assistance',
    rate: '$100/day',
    servicePeriod: '3–7 Feb 2026',
    transactionRef: 'TXN-20260212-003',
  },
  {
    id: 'INV-008',
    dateSubmitted: '8 Feb 2026',
    provider: 'Transport Assist',
    serviceType: 'Accessible Taxi Services',
    amount: 120,
    status: 'Paid',
    paidDate: '9 Feb',
    description: '4x accessible taxi trips to appointments',
    rate: '$30/trip',
    servicePeriod: '3–7 Feb 2026',
    transactionRef: 'TXN-20260209-004',
  },
  {
    id: 'INV-009',
    dateSubmitted: '6 Feb 2026',
    provider: 'Communication Plus',
    serviceType: 'Speech Therapy',
    amount: 280,
    status: 'Paid',
    paidDate: '7 Feb',
    description: '1x 60-min speech therapy session',
    rate: '$180/session',
    servicePeriod: '5 Feb 2026',
    transactionRef: 'TXN-20260207-005',
  },
  {
    id: 'INV-010',
    dateSubmitted: '4 Feb 2026',
    provider: 'Active Kids Physio',
    serviceType: 'Physiotherapy',
    amount: 350,
    status: 'Paid',
    paidDate: '5 Feb',
    description: '2x 45-min physiotherapy sessions',
    rate: '$175/session',
    servicePeriod: '3–4 Feb 2026',
    transactionRef: 'TXN-20260205-006',
  },
  {
    id: 'INV-011',
    dateSubmitted: '1 Feb 2026',
    provider: 'Community Group',
    serviceType: 'Rec Sports Program',
    amount: 150,
    status: 'Paid',
    paidDate: '2 Feb',
    description: 'Monthly recreational sports program participation',
    rate: '$150/month',
    servicePeriod: 'January 2026',
    transactionRef: 'TXN-20260202-007',
  },
  {
    id: 'INV-012',
    dateSubmitted: '30 Jan 2026',
    provider: 'Education Support Services',
    serviceType: 'School Support (5 days)',
    amount: 500,
    status: 'Paid',
    paidDate: '31 Jan',
    description: '5 days school support assistance',
    rate: '$100/day',
    servicePeriod: '20–24 Jan 2026',
    transactionRef: 'TXN-20260131-008',
  },
];
